### ISSUE TITLE
🐳[Feat] 고객/고객 등록-등록

### ISSUE THREAD

**Issue by mini-xi** [1oT-organization/hotelity-frontend#10]
# ⚠️ Issue
> 추가하려는 기능에 대해 간결하게 설명해주세요
- 입력한 값을 바탕으로 DB에 고객 정보 저장

# 📋 Details
> 기능 개발을 위해 어떤 작업을 수행할 것인지 자세히 설명해주세요.
- 등록 버튼을 누를 시 입력한 값이 DB에 저장

# ✏️ ToDoList
- [ ] 새로운 기능 구현 코드 작성
- [ ] 테스트 완료

# 🦉 관련 Issue
> 해당 기능과 관련된 이슈를 ex) #12 형태로 기재해주세요.

**Comment by DYShin1** [comment]
구현 완료.
